#!/usr/bin/env ruby
# coding: utf-8

$:.unshift File.join(File.dirname(__FILE__), *%w[./])

require 'kofu'

if __FILE__ == $0
  
  options = {}  
  
  kofu = OptionParser.new do |opt|
    opt.banner = "Usage: kofu COMMAND [OPTIONS]"
    opt.separator  ""
    opt.separator  "Commands"
    opt.separator  "     process: process csv file"
    opt.separator  ""
    opt.separator  "Options"
    
    opt.on("-l","--lang LANG","target programing language (either ruby or java)") do |lang|
      options[:lang] = lang 
    end
    
    opt.on("-f","--file FILE","the csv file to process") do |file|
      options[:file] = file 
    end
  
    opt.on("-p","--patterns","disclose build attempt patterns") do
      options[:patterns] = true
    end
    
    opt.on("-s","--screen","target programing language (either ruby or java)") do
      options[:screen] = true 
    end
  
    opt.on("-h","--help","help") do 
      puts kofu
    end
  end
  
  kofu.parse!
  
  case ARGV[0]
   when "process"
     if options[:file].nil? and options[:patterns].nil?
       puts "at least one option is required!"
       puts kofu
     else
       file = options[:file].nil? ? 'data.csv' : options[:file] 
       lang = options[:lang].nil? ? 'all' : options[:lang]
     
       if options[:patterns].nil?
         tofile = options[:screen].nil? || !options[:screen]  
         Kofu.dump(Kofu.process(file, lang), tofile)
       else
         Kofu.process(file, lang, options[:patterns])
       end
     end
    else
      puts "command expected!!"
      puts kofu
    end

end