-- MySQL query
-- Copyright Huascar Sanchez, 2016.
SELECT DISTINCT 
		S1.GH_PROJECT_NAME, 
		S1.TR_BUILD_ID, 
		S1.GIT_COMMIT,		
		S1.TR_STATUS, 
		S1.TR_STARTED_AT,
		S1.GH_LANG,
		S1.GIT_BRANCH,
		S1.TR_JOB_ID
FROM travistorrent_7_9_2016 S1 
INNER JOIN (
	SELECT GH_PROJECT_NAME 
	FROM travistorrent_7_9_2016 
	WHERE GH_LANG in ("ruby", "java")
	GROUP BY GH_PROJECT_NAME
) S2 ON S1.GH_PROJECT_NAME = S2.GH_PROJECT_NAME